version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-network
    restart: unless-stopped

  # Library Management Application
  library-app:
    build: .
    container_name: library-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/library_db
      SPRING_DATASOURCE_USERNAME: library_user
      SPRING_DATASOURCE_PASSWORD: library_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - library-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # H2 Database (for development/testing)
  h2-console:
    image: oscarfonts/h2:latest
    container_name: library-h2
    environment:
      H2_OPTIONS: -web -webAllowOthers -tcp -tcpAllowOthers -browser
    ports:
      - "8081:8082"
      - "9092:9092"
    networks:
      - library-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  library-network:
    driver: bridge