version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - library-network

  library-app:
    build: .
    container_name: library-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8090:8080"
    depends_on:
      - mysql-db
    networks:
      - library-network

  h2-console:
    image: oscarfonts/h2:latest
    container_name: library-h2
    ports:
      - "8092:8082"
    networks:
      - library-network

volumes:
  mysql_data:

networks:
  library-network: